apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: payments
spec:
  selector:
    app: payments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: ClusterIP
